

        <ul class = "menu" >

            <li class = "div1"><a href="#"><?=$block->getData('notice1')?></a></li>
            <li class = "div2"><a href="#"> <?=$block->getData('notice2')?></a></li>
            <li class = "div3"><a href="#"> <?=$block->getData('notice3')?></a></li>

        </ul>
        <style>
            ul.menu {
                display: flex;
                justify-content: space-between;
                width: 100%;
                list-style-type: none;
                padding: 0;
                border: 1px solid #000;
            }

           ul.menu li {
               display: inline-block;
               padding: 20px 0 20px 0;
               margin: 0;
               text-align: center;
               width: 32.5%;
               border: 1px solid #000;
           }
            .div2
            {
                background-color: pink;
            }
            .div3
            {
                background-color: orange;
            }
        </style>












